name:Build and Deploy
  on:
   push:
    branches:
      - master
jobs: 
  build:
  
    runs-on: ubuntu-lastest
    
    steps:
    - uses: action/checout@v2
    - name: Angular Deploy gh-pages Actions
      uses: AhsanAyaz/angular-deploy-gh-pages-action@v1.2.0
      with:
        github_access_token: ${{secrets.ACCESS_TOKEN }}
        buil_folder: dist/simple-app
        base_href: /Avril-Terrones/
    
